name: ETL Pipeline Automatique

env:
  ACTIONS_RUNNER_DEBUG: true

on:
  schedule:
    - cron: "0 0 * * *"  # Exécution toutes les heures

jobs:
  run_pipeline:
    runs-on: ubuntu-22.04  # Version plus récente
    steps:
      - name: Cloner le repo
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Mettre à jour pip
        run: python -m pip install --upgrade pip  

      - name: Vérifier requirements.txt
        run: cat requirements.txt

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Rendre etl_flights.py exécutable
        run: chmod +x etl_flights.py

      - name: Exécuter le pipeline ETL
        run: python etl_flights.py